### ISSUE TITLE
[Bug] RelationshipDB CORS Error

### ISSUE THREAD

**Issue by Euro-pol** [verticalsync/Suncord#32]
### Discord Account

confirmedxd

### What happens when the bug or crash occurs?

RelationshipDB cmds don't work.

### What is the expected behaviour?

Commands should work as expected.

### How do you recreate this bug or crash?

- Enable RelationshipDB
- Run /propose
- Nothing will work, because it is missing CORS stuff (so it can't contact webserver).

### Errors

```
Access to fetch at 'https://wedlock.exhq.dev/v2/propose?to=1&msg=Hi' from origin 'https://discord.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Euro-pol** [comment]
Please fix!

**Comment by verticalsync** [comment]
should be fixed, lmk

**Comment by verticalsync** [comment]
won't be fixed, its their api issue not ours
