### ISSUE TITLE
Suncord Plugins Bug

### ISSUE THREAD

**Issue by B3cash** [verticalsync/Suncord#33]
### Discord Account

btcash.

### What happens when the bug or crash occurs?

The bug freezes your discord until you close the error that appears 3 times in a repeated pattern.

### What is the expected behaviour?

I excepted my plugin page/themes to load and ends up freezing constantly an even happens when open some games such as rblx.

### How do you recreate this bug or crash?

1. Have dyslexia font installed.
2. Enable and restart discord.
3. Goto your Plugins page and it should freeze and give the error above.

### Errors

```

JavaScript error:

Uncaught exeption:
    TypeError: Object has been destroyed
    at VencordPatcher<:18:1057904866426630154>1463
    at Timeout._onTimeout(VencordPatcher:17:5275_
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (nod:internal/timers:502:7)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [x] I have read the requirements for opening an issue above

**Comment by verticalsync** [comment]
seems like an issue with just using other fonts, if it happens on vencord itself as well, then probably wont be fixed
