### ISSUE TITLE
cannot install, bricks windows inistall :(

### ISSUE THREAD

**Issue by snoobiegoobert** [verticalsync/Suncord#34]
### Content

wen i do the install, it delte my c -rep
![RAAAAAAAAAAAAAAAAAAAAGH](https://github.com/verticalsync/Suncord/assets/140143172/0954eb9f-56c8-4da4-a150-6c5d6395b864)
pic related

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by verticalsync** [comment]
this is fake.

**Comment by snoobiegoobert** [comment]
this is very real.

**Comment by verticalsync** [comment]
![asasdas](https://github.com/verticalsync/Suncord/assets/60797172/78445374-e27e-494a-99ac-5e2a41c31da4)
