### ISSUE TITLE
Outdated plugins

### ISSUE THREAD

**Issue by D3SOX** [verticalsync/Suncord#87]
I see you're using some of my plugins here. Thanks for the support but I noticed most of them are pretty outdated. Maybe you can make use of git submodules and then use something like Dependabot to get notified for updates :)

**Comment by verticalsync** [comment]
> I see you're using some of my plugins here. Thanks for the support but I noticed most of them are pretty outdated. Maybe you can make use of git submodules and then use something like Dependabot to get notified for updates :)

I've already tried using git submodules, but I'm not the best with git and they were messy to get working imo.

**Comment by D3SOX** [comment]
It's not that hard.
I mean yeah some userplugins are not in the right form for them to allow simply cloning the repo in a `plugins` folder where you would have to resort back to symlinking. The same applies for a repo where you don't want every plugin. (I don't see that as a big problem because users can just leave the other plugins disabled)
Not sure if symlinks work the same on Windows but git definitely supports UNIX symlinks.

To implement this I'd just make a folder like `submodules` somewhere and add them there using `git submodule add <url>`. After that create the corresponding symlinks in your `suncordplugins` folder. Then setup [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) with the `gitsubmodule` option for that folder.

**Comment by verticalsync** [comment]
Thanks for the suggestion, but I'll stick to manually updating. :)
